# docker-compose.yml
version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - ./media:/app/media
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=edufuturo
      - POSTGRES_USER=edu
      - POSTGRES_PASSWORD=securepass
  redis:
    image: redis:7